apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-route
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /first-route
            backend:
              serviceName: first-page-service
              servicePort: 80
          - path: /second-route
            backend:
              serviceName: second-page-service
              servicePort: 80
