apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: sarathps93/ebs-client
      ports:
        - containerPort: 3000
      command: ["sleep2.0"] #Entry Point
      args: ["10"] #Command to run
