apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: sarathps93/ebs-client
      context: nameofyourfolder
      docker:
        dockerfile: dockerfilename
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
    - image: sarathps93/ebs-server
      context: nameofyourfolder
      docker:
        dockerfile: dockerfilename
      sync:
        "**/*.js": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
