apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: domain-com-tls
spec:
  secretName: domain-com
  issuerRef:
    name: letsencryot-prod
    kind: ClusterIssuer
  commonName: sarathps.com
  dnsNames:
    - sarathps.com
    - www.sarathps.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sarathps.com
          - www.sarathps.com
