apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  backoffLimit: 15 # This is so the job does not quit before it succeeds. Default value 6
  completions: 3 # By default creates it sequentially. Specifies how many successful attempts required
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never
