apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data

# Do not use hostPath in production environments. For eg: to use with AWS, refer below
---
awsElasticBlockStore:
  volumeID: <volume-id>
  fsType: ext4
