apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requestes:
      storage: 500Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: sarathps93/ebs-client
      ports:
        - containerPort: 3000
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
