apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: sarathps93/ebs-client
      ports:
        - containerPort: 3000
  tolerations: # All the values has to be defined within quotes
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
